[theme]
#theme = "gruvbox-light"

[icons]
icons = "awesome4"

[[block]]
block = "custom"
command = "waybar-lyric --quiet | head -n 1 | jq -r '.text'"
interval = 0.3
# Hide the block when there's no output
hide_when_empty = true

[[block]]
block = "music"
format = " $icon $prev {$artist.str(max_w:15) $play $next |} "
format_alt = " $icon {$combo.str(max_w:15,rot_interval:0.5) |} "

[[block]]
block = "sound"

[[block]]
block = "net"
format = " $icon $speed_down.eng(prefix:K)^icon_net_down$speed_up.eng(prefix:K)^icon_net_up "
format_alt = " $icon {$signal_strength $ssid |Wired connection} $ip "

[[block]]
block = "nvidia_gpu"
format = " $icon GPU:$utilization\\|$temperature "

[[block]]
block = "cpu"
format = " $icon CPU: $utilization"
[[block]]
block = "temperature"
format = "$max "

[[block]]
block = "memory"
format = " $icon MEM: $mem_total_used_percents.eng(w:2) "

[[block]]
block = "load"
format = " $icon Load: $1m.eng(w:4) "

[[block]]
block = "disk_space"
format = " $icon Turing: $available.eng(w:2) "

[[block]]
block = "battery"
format = " $icon BAT: $percentage "
full_format = " $icon  "

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:1)) |} "
driver = "swaync"
[[block.click]]
button = "left"
action = "show"
[[block.click]]
button = "right"
action = "toggle_paused"

[[block]]
block = "github"
token = "****************************************"
format = " $icon $total.eng(w:1) "
info = ["total"]
warning = ["mention","review_requested"]

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
[block.mappings]
"English (US)" = "qwerty"
"English (Dvorak)" = "dvorak"
"English (Workman)" = "EN"
"German (neo2)" = "neo2"
"Russian (N/A)" = "RU"

[[block]]
block = "time"
[block.format]
full = " $timestamp.datetime(f:'%a: %Y-%m-%d %T', l:hi_IN)"
