[general]
import = [
  "~/.config/alacritty/themes/github_light.toml",
]

[font]
size =  12

[font.normal]
# family = "JetBrainsMono Nerd Font"
family = "Iosevka Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0

# [scrolling]
# history = 0 
